version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgres/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
     - db
    env_file:
     - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/images/
  nginx:
    # образ, из которого должен быть запущен контейнер
    image: nginx:1.21.3-alpine

    # запросы с внешнего порта 80 перенаправляем на внутренний порт 80
    ports:
      - "80:80"

    volumes:
      # При сборке скопировать созданный конфиг nginx из исходной директории 
      # в контейнер и сохранить его в директорию /etc/nginx/conf.d/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/data/www/static/
      - media_value:/data/www/images/

    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - web

volumes:
  static_value:
  media_value:
