version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgres/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
     - db
    env_file:
     - ./.env
    volumes:
      - media_value:/app/images/

volumes:
  media_value:
